title: Author Template

author:
  name: Ernest Hemingway
  email: hemingway@example.com

description: >-
  There is nothing to writing. All you do is sit down at a typewriter and bleed.
baseurl: "/author"
url: "https://easachs.github.io"
twitter_username: DailyHemingway
instagram_username: earnest.hemingway

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
minima:
  hide_site_feed_link: true

collections:
  posts:
    output: true
    permalink: /posts/:name/
  books:
    output: true
    permalink: /books/:name/

google_analytics: "G-RS80H21YWV"
